"""
Import Buildings + Building Operators from the QuadReal Industrial DB Excel
export into roster-data.js for the Work Safe app.
"""
from __future__ import annotations

import json
import math
import re
from pathlib import Path

import pandas as pd

XLSX = Path(r"c:\Users\Robert\Downloads\QuadReal_Industrial_DB_Export_2026.07.27.xlsx")
OUT = Path(__file__).resolve().parents[1] / "roster-data.js"


def clean(s) -> str:
    if s is None or (isinstance(s, float) and math.isnan(s)):
        return ""
    t = str(s).strip()
    if t.lower() in ("nan", "none", "-"):
        return ""
    # Strip portfolio count suffixes like "(x 22)"
    t = re.sub(r"\s*\(x\s*\d+\)\s*$", "", t).strip()
    return t


def phone_e164(raw: str) -> str | None:
    if not raw:
        return None
    digits = re.sub(r"\D", "", raw)
    if len(digits) == 10:
        return "+1" + digits
    if len(digits) == 11 and digits.startswith("1"):
        return "+" + digits
    if 10 <= len(digits) <= 15:
        return "+" + digits
    return None


def main() -> None:
    buildings_df = pd.read_excel(XLSX, sheet_name="Buildings")
    ops_df = pd.read_excel(XLSX, sheet_name="Building Operators")

    buildings = []
    for _, row in buildings_df.iterrows():
        addr = clean(row.get("Building Address"))
        if not addr:
            continue
        lat = row.get("Latitude")
        lng = row.get("Longitude")
        try:
            lat_f = float(lat)
            lng_f = float(lng)
        except (TypeError, ValueError):
            lat_f = lng_f = None
        if lat_f == 0 and lng_f == 0:
            lat_f = lng_f = None
        buildings.append(
            {
                "address": addr,
                "bu": clean(row.get("BU #")),
                "portfolio": clean(row.get("Portfolio")),
                "cluster": clean(row.get("Cluster")),
                "manager": clean(row.get("Manager")),
                "lat": lat_f,
                "lng": lng_f,
            }
        )

    # people[name] = { name, roles: set, phones: set, buildings: set }
    people: dict[str, dict] = {}

    def add_person(name: str, role: str, phone: str | None = None, building: str | None = None):
        name = clean(name)
        role = clean(role)
        if not name or not role:
            return
        # Skip region tags alone
        if name.lower() in ("west", "east"):
            return
        # Ops manager cells look like "Eldin Shima (West)" — keep full label as name
        entry = people.setdefault(
            name.lower(),
            {"name": name, "roles": set(), "phones": set(), "buildings": set()},
        )
        # Prefer Title Case display if we had lowercase key collision
        if len(name) > len(entry["name"]):
            entry["name"] = name
        entry["roles"].add(role)
        if phone:
            e164 = phone_e164(phone)
            if e164:
                entry["phones"].add(e164)
        if building:
            entry["buildings"].add(building)

    for _, row in ops_df.iterrows():
        addr = clean(row.get("Building Address"))
        if not addr:
            continue
        add_person(row.get("Property Manager"), "Property Manager", building=addr)
        add_person(
            row.get("Building Operator"),
            "Building Operator",
            phone=clean(row.get("Operator Phone")),
            building=addr,
        )
        add_person(row.get("Ops Manager (Region)"), "Ops Manager", building=addr)
        add_person(row.get("GM Ops"), "GM Ops", building=addr)
        add_person(row.get("VP"), "VP", building=addr)

    # Also managers from Buildings sheet
    for b in buildings:
        if b["manager"]:
            add_person(b["manager"], "Property Manager", building=b["address"])

    people_out = []
    for p in people.values():
        people_out.append(
            {
                "name": p["name"],
                "roles": sorted(p["roles"]),
                "phones": sorted(p["phones"]),
                "buildings": sorted(p["buildings"]),
            }
        )
    people_out.sort(key=lambda x: x["name"].lower())
    buildings.sort(key=lambda x: x["address"].lower())

    payload = {
        "source": XLSX.name,
        "buildings": buildings,
        "people": people_out,
    }

    js = (
        "/* Auto-generated by scripts/import-roster.py — do not edit by hand. */\n"
        "window.WORK_SAFE_ROSTER = "
        + json.dumps(payload, ensure_ascii=False, indent=2)
        + ";\n"
    )
    OUT.write_text(js, encoding="utf-8")
    print(f"Wrote {OUT}")
    print(f"  buildings: {len(buildings)}")
    print(f"  people:    {len(people_out)}")


if __name__ == "__main__":
    main()
